version: '3.4'

services:
    parser:
        image: leigholiver/replaybot_parser
        build: ./replaybot_parser
        network_mode: host
        #environment:
        #    - NEWRELIC_LICENSE_KEY

    discord:
        image: leigholiver/replaybot_discord
        build: ./replaybot_discord
        network_mode: host
        environment:
            - NEWRELIC_LICENSE_KEY
            - BOT_TOKEN
            - BOT_SHARED_KEY
            - "PARSER_ENDPOINT=http://localhost:5001"
            - "API_ENDPOINT=http://localhost:5000/api"
            #- "API_ENDPOINT=https://preprod.replaybot.com/api"
