apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord
spec:
  template:
    spec:
      containers:
        - name: discord
          image: leigholiver/replaybot_discord_preprod
          env:
            - name: NEW_RELIC_APP_NAME
              value: replaybot_discord_preprod
            - name: API_ENDPOINT
              value: https://api-preprod.replaybot.com/api
