apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  template:
    spec:
      containers:
        - name: search
          image: leigholiver/replaybot_search_preprod
          env:
            - name: NEW_RELIC_APP_NAME
              value: replaybot_search_preprod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: search
  annotations:
    external-dns.alpha.kubernetes.io/hostname: search-preprod.replaybot.com
spec:
  tls:
  - hosts:
    - search-preprod.replaybot.com
    secretName: search-tls
  rules:
  - host: search-preprod.replaybot.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: search
            port:
              number: 80
