name: Build-Discord
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/Build-Discord.yml"
      - "discord/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Build Image
        run: |
          docker build -t ${{ secrets.dockerhubUsername }}/replaybot_discord discord
      
      - name: Login to docker repos
        run: echo ${{ secrets.dockerhubPassword }} | docker login -u ${{ secrets.dockerhubUsername }} --password-stdin
      
      - name: Tag and push
        run: |
          docker tag ${{ secrets.dockerhubUsername }}/replaybot_discord ${{ secrets.dockerhubUsername }}/replaybot_discord:latest
          docker push ${{ secrets.dockerhubUsername }}/replaybot_discord:latest