name: Kubernetes
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/Kubernetes.yml"
      - "kubernetes/base/**"
      - "kubernetes/overlay/prod/**"
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Run Kustomize
        working-directory: ./kubernetes
        run: kubectl kustomize overlay/prod > replaybot-prod.yml

      - name: Commit to platform repo
        uses: leigholiver/commit-with-deploy-key@v1.0.2
        with:
          source: kubernetes/replaybot-prod.yml
          destination_folder: resources/replaybot
          destination_repo: leigholiver/platform
          destination_branch: master
          deploy_key: ${{ secrets.DEPLOY_KEY }}
