name: Deployment
on:
  push:
    branches:
      - master
      - preprod
    paths:
      - ".github/workflows/Run-Deploy.yml"
      - "web/api/**"
      - "web/environment/**"
      - "web/framework/**"
      - "web/frontend/**"
      - "web/main.tf"
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.28

      - name: Install dependencies
        working-directory: ./web
        run: |
          python -m pip install --upgrade pip
          pip install -r framework/requirements.txt
          pip install -r api/packages.txt

      - name: Install frontend dependencies
        working-directory: ./web/frontend
        run: |
          yarn install

      - name: Run deployment
        working-directory: ./web
        run: |
          echo "${{ secrets.secrets }}" > secrets.env
          ./lambctl deploy -y
