name: Deployment
on:
  push:
    branches:
      - master
      - preprod
    paths:
      - ".github/workflows/Run-Deploy.yml"
      - "replaybot_web/**"
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'

      - name: Install dependencies
        working-directory: ./replaybot_web
        run: |
          python -m pip install --upgrade pip
          pip install -r framework/requirements.txt
          pip install -r api/packages.txt
          
      - name: Install frontend dependencies
        working-directory: ./replaybot_web/frontend
        run: |
          yarn install

      - name: Run deployment
        working-directory: ./replaybot_web
        run: |
          echo "${{ secrets.secrets }}" > secrets.env
          ./lambctl deploy -y